### ISSUE TITLE
bugfix-improvement

### ISSUE THREAD

**Issue by PhantomDevTeam** [PhantomDevTeam/PDT-H60-Startup#1]
- [x] Bug #1: Incorrect function call in mission.sqm: https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/502a4a8851f40e9a4744fd16a8bb9c2c77accdaf/PDT_H60_AI_Startup.Stratis/mission.sqm#L14813.
- [x] Bug #2: Incorrect variable in fn_getTargets: https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/502a4a8851f40e9a4744fd16a8bb9c2c77accdaf/PDT_H60_AI_Startup.Stratis/functions/h60_startup/doorguns/fn_getTargets.sqf#L43 and https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/502a4a8851f40e9a4744fd16a8bb9c2c77accdaf/PDT_H60_AI_Startup.Stratis/functions/h60_startup/doorguns/fn_getTargets.sqf#L65
- [x] Improvement #1: Move the CfgFunctions class from https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/main/PDT_H60_AI_Startup.Stratis/configs/CfgFunctions.hpp to https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/main/PDT_H60_AI_Startup.Stratis/description.ext for ease of implementation into other missions.
- [x] Improvement #2: Remove https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/main/PDT_H60_AI_Startup.Stratis/functions/h60_startup/misc/fn_lightsOff.sqf and https://github.com/PhantomDevTeam/PDT-H60-Startup/blob/main/PDT_H60_AI_Startup.Stratis/functions/h60_startup/misc/fn_lightsOn.sqf then replace with a single file.
- [x] Improvement #3: Allow lights to be turned on and allow the various brightness levels to be used.
- [x] Documentation #1: Create a written tutorial on how to implement the scripts in other missions.
